#
# My default bash prompt theme
#

add_newline = false

# A minimal left prompt
format = """
$line_break\
${custom.dirname}\
${custom.basename}\
$git_branch\
${custom.git_status_dirty}\
$git_status
$python\
$character\
"""

# Move the rest of the prompt to the right
right_format = """
$all$status$cmd_duration
"""

# Timeout for commands executed by starship (in milliseconds)
command_timeout = 2000

# Set the palette.
palette = "wombat_256"

# Define custom colors
[palettes.tokyo_night_256]
black = '16'
blue = '111'
cyan = '117'
green = '149'
purple = '141'
red = '210'
white = '146'
yellow = '179'

[palettes.wombat_256]
black = '0'
blue = '75'
cyan = '123'
green = '149'
purple = '171'
red = '203'
white = '188'
yellow = '223'
true_white = '255'

[palettes.p10k]
black = '0'
blue = '31'
cyan = '39'
green = '76'
purple = '205'
magenta = '205'
red = '204'
white = '223'
yellow = '226'

[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'
vicmd_symbol = '[vi\$](bold white)'

[python]
format = '[(\($virtualenv\) )]($style)'
style = 'white'

[directory]
style = "bold cyan"
truncate_to_repo = false
disabled = true

[git_branch]
format = '[$branch]($style)'
style = 'purple'

[git_status]
format = '( [\[$ahead_behind$stashed\]]($style))'
style = "cyan"
stashed = "≡"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = "•"
style = "yellow"
format = "[$symbol]($style)"
shell = ["sh"]

[custom.dirname]
when = true
command = 'test "$PWD" != "$HOME" && printf "%s/\n" "$(dirname "$PWD")" | sed -E "s|$HOME/|\~/|"'
format = '[$symbol($output)]($style)'
style = "blue"
disabled = false
shell = ["sh"]

[custom.basename]
when = true
command = 'test "$PWD" = "$HOME" && echo "~" || basename "$PWD" | sed -E "s|$HOME/|\~/|"'
style = "bold cyan"
disabled = false
shell = ["sh"]

[custom.todo]
when = 'test $(todo.sh ls | wc -l) -gt 2'
command = 'todo.sh ls | tail -n 1 | cut -d" " -f2'
symbol = "☑"
format = '[$symbol( $output)]($style)'
style = "blue"
disabled = false
shell = ["sh"]

[cmd_duration]
format = ' [$duration]($style)'

[line_break]
disabled = false

[status]
disabled = false
format = ' [$symbol$int]($style)'
symbol = '✘'
pipestatus = true
pipestatus_format = '\[$pipestatus\]($style)'
