add_newline = false

[character]
success_symbol = "[%%](purple)"
error_symbol = "[%%](red)"
vicmd_symbol = "[vi%%](bold green)"

[directory]
style = "blue"
repo_root_style = "blue"
truncate_to_repo = false
truncation_length = 0
disabled = false

[cmd_duration]
format = "[$duration](yellow)"

[git_branch]
style = "bright-black"
format = "[$branch]($style)"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style) "
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[status]
style = "red"
format = '[\[$int\]]($style) '
disabled = false
