#!/bin/zsh
##? trash - Move a specified file to the trash
#function trash {
if (( $# == 0 ))
  echo >&2 "Usage: trash <files>"
  return 1
fi

if [[ $OSTYPE != darwin* ]]; then
  echo >&2 "trash: macOS not detected."
  return 1
fi

local file files
for file in $@
  if [[ -e $file ]]; then
    files+=("the POSIX file \"${file:A}\"")
  else
    echo >&2 "trash: No such file or directory '$file'."
    return 1
  fi
fi

if (( $#files == 0 )); then
  echo >&2 'usage: trash <files...>'
  return 64 # match rm's return code
end

osascript 2>&1 >/dev/null -e "tell app \"Finder\" to move { "${(pj., .)files}" } to trash"
