#!/bin/zsh
# zsh_unplugged
local plugdir
local pluginroot
if [[ $1 == '--dir' ]]; then
  shift; pluginroot=$1; shift
else
  pluginroot=${ZPLUGINDIR:-${ZDOTDIR:-$HOME/.config/zsh}/plugins}
fi
for plugdir in $@; do
  [[ $plugdir = /* ]] || plugdir=$pluginroot/$plugdir
  fpath+=$plugdir
  local initfile=$plugdir/${plugdir:t}.plugin.zsh
  (( $+functions[zsh-defer] )) && zsh-defer . $initfile || . $initfile
done
