add_newline = false

# A minimal left prompt
format = """$python$directory$character"""

# move the rest of the prompt to the right
#right_format = """$status$git_branch${custom.git_status_dirty}$git_status"""
right_format = """$status$cmd_duration$git_branch${custom.git_status_dirty}$git_status"""

[character]
success_symbol = "[❯](white)[❯](green)"
error_symbol = "[❯](yellow)[❯](red)"
vicmd_symbol = "[❮](green❮](white)"

[python]
format = '\($virtualenv\) '

[directory]
style = "blue"
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

# right prompt uses left space padding
[git_branch]
format = ' [$branch]($style)'
style = 'purple'

[git_status]
format = '( [\[$ahead_behind$stashed\]]($style))'
style = "cyan"
stashed = "≡"
ahead = "⇡${count}"
behind = "⇣${count}"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = "•"
style = "white"
format="[$symbol]($style)"
shell = ["sh"]

[cmd_duration]
format = ' [$duration]($style)'

[line_break]
disabled = true

[status]
disabled = false
symbol = ' ✘'
