#
# mmc - mattmc3's starship config
#

add_newline = false

# A minimal left prompt
format = """$python$directory$character"""

# Move the rest of the prompt to the right
right_format = """$status$cmd_duration$git_branch${custom.git_status_dirty}$git_status$shell"""

# Timeout for commands executed by starship (in milliseconds)
command_timeout=2000

# Set the color palette
palette = "tokyonight"

# Define custom colors
[palettes.tokyonight]
black = '#15161e'
blue = '#7aa2f7'
cyan = '#7dcfff'
green = '#9ece6a'
magenta = '#bb9af7'
red = '#f7768e'
white = '#a9b1d6'
yellow = '#e0af68'
pink = '#ff6ac1'

[character]
success_symbol = "[❱](pink)"
error_symbol = "[❱](red)"
vicmd_symbol = "[❰](cyan)"

[python]
format = '[(\($virtualenv\) )]($style)'
style = 'cyan'

[directory]
style = "blue"
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

# Right-side prompt items use left space padding
[git_branch]
format = ' [$branch]($style)'
style = 'white'

[git_status]
format = "[( $ahead_behind$stashed)]($style)"
style = "cyan"
stashed = "≡"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = "＊"  # • * ﹡ ＊ ✱
style = "purple"
format="[$symbol]($style)"
shell = ["sh"]

[shell]
fish_indicator = ' 🐟'  # 󰈺 🐟 🐠
powershell_indicator = ' _'
pwsh_indicator = ' _'
zsh_indicator = '󠀥 %'
style = 'cyan bold'
disabled = false

[cmd_duration]
format = ' [$duration]($style)'

[line_break]
disabled = true

[status]
disabled = false
pipestatus = true
format = '[$symbol$int]($style)'
symbol = '✘'
pipestatus_format = '\[$pipestatus\]($style)'
