add_newline = false

# A minimal left prompt
format = """$directory$character"""

# move the rest of the prompt to the right
right_format = """$status$time$git_branch${custom.git_status_dirty}$git_status"""

[character]
success_symbol = '[⋊>](cyan)'
error_symbol = '[⋊>](bold red)'
vicmd_symbol = '[vi ⋊>](blue)'

[directory]
style = "white"
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

# right prompt uses left space padding
[git_branch]
format = ' [$branch]($style)'
style = 'bold green'

[git_status]
format = '[$all_status$ahead_behind]($style)'
ahead = '↑'
behind = '↓'
stashed = '≡'
modified = '⨯'
diverged = '⥄'
style = "purple"

[time]
format = '[$time]($style)'
disabled = false

[line_break]
disabled = true

[status]
disabled = false
symbol = ' ✘'

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = "⨯"
style = "purple"
format="[$symbol]($style)"
shell = ["sh"]
